# Generated by Django 4.2 on 2023-05-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_brand_slud_brand_watch_slud_alter_brand_watch_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slud',
        ),
        migrations.RemoveField(
            model_name='brand_watch',
            name='slud',
        ),
    ]
