# Generated by Django 4.2 on 2023-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0006_brand_watch_watch_price_alter_brand_brand_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand_watch',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
