# Generated by Django 4.2 on 2023-05-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0007_brand_watch_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_watch',
            name='watch_price',
            field=models.CharField(max_length=30),
        ),
    ]
